# Supabase Configuration
# Generated: 2026-02-27

project_id = "kteobfyferrukqeolofj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false

[studio]
enabled = true
port = 54323

[inbucket]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://javariai.com"
additional_redirect_urls = ["https://craudiovizai.com"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
